<?php


/**
 * Base class that represents a query for the 'jugador_mesa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 10/31/15 22:35:50
 *
 * @method JugadorMesaQuery orderById($order = Criteria::ASC) Order by the id column
 * @method JugadorMesaQuery orderByMesaId($order = Criteria::ASC) Order by the mesa_id column
 * @method JugadorMesaQuery orderByEstado($order = Criteria::ASC) Order by the estado column
 * @method JugadorMesaQuery orderByJugadorId($order = Criteria::ASC) Order by the jugador_id column
 * @method JugadorMesaQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method JugadorMesaQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method JugadorMesaQuery orderByCreatedBy($order = Criteria::ASC) Order by the created_by column
 * @method JugadorMesaQuery orderByUpdatedBy($order = Criteria::ASC) Order by the updated_by column
 *
 * @method JugadorMesaQuery groupById() Group by the id column
 * @method JugadorMesaQuery groupByMesaId() Group by the mesa_id column
 * @method JugadorMesaQuery groupByEstado() Group by the estado column
 * @method JugadorMesaQuery groupByJugadorId() Group by the jugador_id column
 * @method JugadorMesaQuery groupByCreatedAt() Group by the created_at column
 * @method JugadorMesaQuery groupByUpdatedAt() Group by the updated_at column
 * @method JugadorMesaQuery groupByCreatedBy() Group by the created_by column
 * @method JugadorMesaQuery groupByUpdatedBy() Group by the updated_by column
 *
 * @method JugadorMesaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method JugadorMesaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method JugadorMesaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method JugadorMesaQuery leftJoinMesa($relationAlias = null) Adds a LEFT JOIN clause to the query using the Mesa relation
 * @method JugadorMesaQuery rightJoinMesa($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Mesa relation
 * @method JugadorMesaQuery innerJoinMesa($relationAlias = null) Adds a INNER JOIN clause to the query using the Mesa relation
 *
 * @method JugadorMesaQuery leftJoinJugador($relationAlias = null) Adds a LEFT JOIN clause to the query using the Jugador relation
 * @method JugadorMesaQuery rightJoinJugador($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Jugador relation
 * @method JugadorMesaQuery innerJoinJugador($relationAlias = null) Adds a INNER JOIN clause to the query using the Jugador relation
 *
 * @method JugadorMesaQuery leftJoinTurno($relationAlias = null) Adds a LEFT JOIN clause to the query using the Turno relation
 * @method JugadorMesaQuery rightJoinTurno($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Turno relation
 * @method JugadorMesaQuery innerJoinTurno($relationAlias = null) Adds a INNER JOIN clause to the query using the Turno relation
 *
 * @method JugadorMesa findOne(PropelPDO $con = null) Return the first JugadorMesa matching the query
 * @method JugadorMesa findOneOrCreate(PropelPDO $con = null) Return the first JugadorMesa matching the query, or a new JugadorMesa object populated from the query conditions when no match is found
 *
 * @method JugadorMesa findOneById(int $id) Return the first JugadorMesa filtered by the id column
 * @method JugadorMesa findOneByMesaId(int $mesa_id) Return the first JugadorMesa filtered by the mesa_id column
 * @method JugadorMesa findOneByEstado(string $estado) Return the first JugadorMesa filtered by the estado column
 * @method JugadorMesa findOneByJugadorId(int $jugador_id) Return the first JugadorMesa filtered by the jugador_id column
 * @method JugadorMesa findOneByCreatedAt(string $created_at) Return the first JugadorMesa filtered by the created_at column
 * @method JugadorMesa findOneByUpdatedAt(string $updated_at) Return the first JugadorMesa filtered by the updated_at column
 * @method JugadorMesa findOneByCreatedBy(string $created_by) Return the first JugadorMesa filtered by the created_by column
 * @method JugadorMesa findOneByUpdatedBy(string $updated_by) Return the first JugadorMesa filtered by the updated_by column
 *
 * @method array findById(int $id) Return JugadorMesa objects filtered by the id column
 * @method array findByMesaId(int $mesa_id) Return JugadorMesa objects filtered by the mesa_id column
 * @method array findByEstado(string $estado) Return JugadorMesa objects filtered by the estado column
 * @method array findByJugadorId(int $jugador_id) Return JugadorMesa objects filtered by the jugador_id column
 * @method array findByCreatedAt(string $created_at) Return JugadorMesa objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return JugadorMesa objects filtered by the updated_at column
 * @method array findByCreatedBy(string $created_by) Return JugadorMesa objects filtered by the created_by column
 * @method array findByUpdatedBy(string $updated_by) Return JugadorMesa objects filtered by the updated_by column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseJugadorMesaQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseJugadorMesaQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'JugadorMesa', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new JugadorMesaQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     JugadorMesaQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return JugadorMesaQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof JugadorMesaQuery) {
            return $criteria;
        }
        $query = new JugadorMesaQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   JugadorMesa|JugadorMesa[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = JugadorMesaPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(JugadorMesaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   JugadorMesa A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `MESA_ID`, `ESTADO`, `JUGADOR_ID`, `CREATED_AT`, `UPDATED_AT`, `CREATED_BY`, `UPDATED_BY` FROM `jugador_mesa` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new JugadorMesa();
            $obj->hydrate($row);
            JugadorMesaPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return JugadorMesa|JugadorMesa[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|JugadorMesa[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(JugadorMesaPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(JugadorMesaPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(JugadorMesaPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the mesa_id column
     *
     * Example usage:
     * <code>
     * $query->filterByMesaId(1234); // WHERE mesa_id = 1234
     * $query->filterByMesaId(array(12, 34)); // WHERE mesa_id IN (12, 34)
     * $query->filterByMesaId(array('min' => 12)); // WHERE mesa_id > 12
     * </code>
     *
     * @see       filterByMesa()
     *
     * @param     mixed $mesaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByMesaId($mesaId = null, $comparison = null)
    {
        if (is_array($mesaId)) {
            $useMinMax = false;
            if (isset($mesaId['min'])) {
                $this->addUsingAlias(JugadorMesaPeer::MESA_ID, $mesaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($mesaId['max'])) {
                $this->addUsingAlias(JugadorMesaPeer::MESA_ID, $mesaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::MESA_ID, $mesaId, $comparison);
    }

    /**
     * Filter the query on the estado column
     *
     * Example usage:
     * <code>
     * $query->filterByEstado('fooValue');   // WHERE estado = 'fooValue'
     * $query->filterByEstado('%fooValue%'); // WHERE estado LIKE '%fooValue%'
     * </code>
     *
     * @param     string $estado The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByEstado($estado = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($estado)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $estado)) {
                $estado = str_replace('*', '%', $estado);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::ESTADO, $estado, $comparison);
    }

    /**
     * Filter the query on the jugador_id column
     *
     * Example usage:
     * <code>
     * $query->filterByJugadorId(1234); // WHERE jugador_id = 1234
     * $query->filterByJugadorId(array(12, 34)); // WHERE jugador_id IN (12, 34)
     * $query->filterByJugadorId(array('min' => 12)); // WHERE jugador_id > 12
     * </code>
     *
     * @see       filterByJugador()
     *
     * @param     mixed $jugadorId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByJugadorId($jugadorId = null, $comparison = null)
    {
        if (is_array($jugadorId)) {
            $useMinMax = false;
            if (isset($jugadorId['min'])) {
                $this->addUsingAlias(JugadorMesaPeer::JUGADOR_ID, $jugadorId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($jugadorId['max'])) {
                $this->addUsingAlias(JugadorMesaPeer::JUGADOR_ID, $jugadorId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::JUGADOR_ID, $jugadorId, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(JugadorMesaPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(JugadorMesaPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(JugadorMesaPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(JugadorMesaPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the created_by column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedBy('fooValue');   // WHERE created_by = 'fooValue'
     * $query->filterByCreatedBy('%fooValue%'); // WHERE created_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $createdBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByCreatedBy($createdBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($createdBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $createdBy)) {
                $createdBy = str_replace('*', '%', $createdBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::CREATED_BY, $createdBy, $comparison);
    }

    /**
     * Filter the query on the updated_by column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedBy('fooValue');   // WHERE updated_by = 'fooValue'
     * $query->filterByUpdatedBy('%fooValue%'); // WHERE updated_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $updatedBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function filterByUpdatedBy($updatedBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($updatedBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $updatedBy)) {
                $updatedBy = str_replace('*', '%', $updatedBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(JugadorMesaPeer::UPDATED_BY, $updatedBy, $comparison);
    }

    /**
     * Filter the query by a related Mesa object
     *
     * @param   Mesa|PropelObjectCollection $mesa The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   JugadorMesaQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByMesa($mesa, $comparison = null)
    {
        if ($mesa instanceof Mesa) {
            return $this
                ->addUsingAlias(JugadorMesaPeer::MESA_ID, $mesa->getId(), $comparison);
        } elseif ($mesa instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(JugadorMesaPeer::MESA_ID, $mesa->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByMesa() only accepts arguments of type Mesa or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Mesa relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function joinMesa($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Mesa');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Mesa');
        }

        return $this;
    }

    /**
     * Use the Mesa relation Mesa object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   MesaQuery A secondary query class using the current class as primary query
     */
    public function useMesaQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinMesa($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Mesa', 'MesaQuery');
    }

    /**
     * Filter the query by a related Jugador object
     *
     * @param   Jugador|PropelObjectCollection $jugador The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   JugadorMesaQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByJugador($jugador, $comparison = null)
    {
        if ($jugador instanceof Jugador) {
            return $this
                ->addUsingAlias(JugadorMesaPeer::JUGADOR_ID, $jugador->getId(), $comparison);
        } elseif ($jugador instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(JugadorMesaPeer::JUGADOR_ID, $jugador->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByJugador() only accepts arguments of type Jugador or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Jugador relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function joinJugador($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Jugador');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Jugador');
        }

        return $this;
    }

    /**
     * Use the Jugador relation Jugador object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   JugadorQuery A secondary query class using the current class as primary query
     */
    public function useJugadorQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinJugador($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Jugador', 'JugadorQuery');
    }

    /**
     * Filter the query by a related Turno object
     *
     * @param   Turno|PropelObjectCollection $turno  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   JugadorMesaQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTurno($turno, $comparison = null)
    {
        if ($turno instanceof Turno) {
            return $this
                ->addUsingAlias(JugadorMesaPeer::ID, $turno->getJugadorMesaId(), $comparison);
        } elseif ($turno instanceof PropelObjectCollection) {
            return $this
                ->useTurnoQuery()
                ->filterByPrimaryKeys($turno->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByTurno() only accepts arguments of type Turno or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Turno relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function joinTurno($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Turno');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Turno');
        }

        return $this;
    }

    /**
     * Use the Turno relation Turno object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TurnoQuery A secondary query class using the current class as primary query
     */
    public function useTurnoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinTurno($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Turno', 'TurnoQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   JugadorMesa $jugadorMesa Object to remove from the list of results
     *
     * @return JugadorMesaQuery The current query, for fluid interface
     */
    public function prune($jugadorMesa = null)
    {
        if ($jugadorMesa) {
            $this->addUsingAlias(JugadorMesaPeer::ID, $jugadorMesa->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
