generator:
  class: sfPropelGenerator
  param:
    model_class:           producto
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              producto
    plural:                productos
    route_prefix:          producto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:           [descripcion, marca, tipo_producto]
        title:             Listado de Productos
      filter:
        display:           [descripcion, marca_id, tipo_producto_id]
      form: 
        display:           [descripcion, marca_id, tipo_producto_id]
      edit:
        title:             Editar Producto
      new:
        title:             Nuevo Producto
