generator:
  class: sfPropelGenerator
  param:
    model_class:           tipoTransaccion
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              tipoTransaccion
    plural:                tipoTransaccions
    route_prefix:          tipo_transaccion
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:             Listado de Tipos de Transaccion
        display:           [descripcion]
      filter:
        display:           [descripcion]
      form:
        display:           [descripcion]
      edit:
        title:             Editar Tipo de Transaccion
      new:
        title:             Nuevo Tipo de Transaccion
