generator:
  class: sfPropelGenerator
  param:
    model_class:           producto
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              producto
    plural:                productos
    route_prefix:          producto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        cantidad_minima:   
          label:           Existencia Minima
        imagen:
          label:           Imagen
          
      list:
        display:           [descripcion, marca,_foto, tipo_producto, tipo_presentacion,cantidad_minima, costo, precio]
        title:             Listado de Productos
      filter:
        display:           [descripcion, marca_id, tipo_producto_id]
      form: 
        display:           [descripcion,imagen,_imagenFoto  , marca_id, tipo_producto_id, tipo_presentacion_id,cantidad_minima, costo, precio]
      edit:
        title:             Editar Producto
      new:
        title:             Nuevo Producto
