generator:
  class: sfPropelGenerator
  param:
    model_class:           tipoPago
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              tipoPago
    plural:                tipoPagos
    route_prefix:          tipo_pago
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:             Listado de Tipos de Pago
        display:           [nombre, descripcion]
      filter:
        display:           [nombre, descripcion]
      form:    
        display:           [nombre, descripcion]
      edit:
        title:             Editar Tipo de Pago
      new:
        title:             Nuevo Tipo de Pago
