<?php



/**
 * Skeleton subclass for performing query and update operations on the 'jugador' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 10/31/15 17:49:15
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class JugadorPeer extends BaseJugadorPeer
{
}
