tipo_presentacion:
  class: sfPropelORMRouteCollection
  options:
    model:                tipoPresentacion
    module:               tipo_presentacion
    prefix_path:          /tipo_presentacion
    column:               id
    with_wildcard_routes: true

producto:
  class: sfPropelORMRouteCollection
  options:
    model:                producto
    module:               producto
    prefix_path:          /producto
    column:               id
    with_wildcard_routes: true

tipo_usuario:
  class: sfPropelORMRouteCollection
  options:
    model:                tipoUsuario
    module:               tipo_usuario
    prefix_path:          /tipo_usuario
    column:               id
    with_wildcard_routes: true

tipo_transaccion:
  class: sfPropelORMRouteCollection
  options:
    model:                tipoTransaccion
    module:               tipo_transaccion
    prefix_path:          /tipo_transaccion
    column:               id
    with_wildcard_routes: true

tipo_producto:
  class: sfPropelORMRouteCollection
  options:
    model:                tipoProducto
    module:               tipo_producto
    prefix_path:          /tipo_producto
    column:               id
    with_wildcard_routes: true

tipo_pago:
  class: sfPropelORMRouteCollection
  options:
    model:                tipoPago
    module:               tipo_pago
    prefix_path:          /tipo_pago
    column:               id
    with_wildcard_routes: true

proveedor:
  class: sfPropelORMRouteCollection
  options:
    model:                proveedor
    module:               proveedor
    prefix_path:          /proveedor
    column:               id
    with_wildcard_routes: true

marca:
  class: sfPropelORMRouteCollection
  options:
    model:                marca
    module:               marca
    prefix_path:          /marca
    column:               id
    with_wildcard_routes: true

cliente:
  class: sfPropelORMRouteCollection
  options:
    model:                cliente
    module:               cliente
    prefix_path:          /cliente
    column:               id
    with_wildcard_routes: true

usuario:
  class: sfPropelORMRouteCollection
  options:
    model:                usuario
    module:               usuario
    prefix_path:          /usuario
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: inicio, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
