propel:
    usuario:
      id:                                ~
      usuario:                           { type: varchar(32), required: true }
      clave:                             { type: varchar(40) }
      nombre:                            { type: varchar(60), required: true, primaryString: true }
      apellido:                          { type: varchar(60), required: true }
      administrador:                     { type: boolean, default: false }
      created_at:                        ~
      updated_at:                        ~
      created_by:                        { type: varchar(32) }
      updated_by:                        { type: varchar(32) }
      _uniques:
        llave:                           [ usuario ]    
    cliente: 
        id:                              ~
        nombre:         { type:varchar(70), required:true } 
        correo:         {type:varchar(70),required:false}
        direccion:      {type:varchar(100),required:false}
        telefono:       {type:varchar(100),required:false}
        ciudad:         {type:varchar(50),required:false}
        observacion:    {type:varchar(120),required:false}
    detalle_pedido_proveedor:
        id:              ~
        producto_id:     ~
        cantidad:       {type:integer,required:false}
        estado:         {type:varchar(20),required:true}
        pedido_proveedor_id:   ~
    marca:
        id:        ~
        nombre:         {type:varchar(30),required:true}
        descripcion:    {type:varchar(60),required:false}
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    pedido_proveedor:
        id:              ~
        fecha:          {type:date,required:true}
        descripcion:    {type:varchar(25),required:false}
        estado:         {type:varchar(30),required:true}
        usuario_id:      ~
        proveedor_id:    ~
    promocion:
        id:    ~
        descripcion:    {type:varchar(70),required:false}
        fecha_inicio:   {type:date,required:true}
        fecha_fin:     {type:date,required:true}
        estado:    {type:varchar(11),required:false}
        producto_id:     ~
        descuento:      {type:decimal,required:false}
        promocion_global:         {type:boolean,required:true}
    proveedor:
        id:    ~
        nombre:         {type:varchar(70),required:true}
        direccion:      {type:varchar(70),required:true}
        correo_eletronico: {type:varchar(70),required:true}
        nombre_contacto: {type:varchar(70),required:false}
        telefono:       {type:varchar(30),required:true}
        ciudad:         {type: varchar(30),required:false}
        observacion:    {type:varchar(70),required:false}
    tipo_pago:
        id:     ~
        nombre:         {type:varchar(30),required:true}
        descripcion:    {type:varchar(70),required:false}
    tipo_producto:
        id: ~
        nombre:         {type:varchar(70),required:true}
        descripcion:    {type:varchar(120),required:false}
    tipo_transaccion:
        id: ~
        descripcion:    {type:varchar(60),required:true}
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    tipo_usuario:
        id:      ~
        nombre:         {type:varchar(30),required:true}
        descripcion:    {type:varchar(120),required:false}
    transaccion:
        id: ~
        serie: {type:varchar(120),required:false}
        documento: {type:varchar(120),required:false}
        cliente_id: ~
        usuario_id: ~
        tipo_transaccion_id: ~
        no_tarjeta: {type:varchar(60),required:false}
        total: {type:decimal,required:false}
        direccion: {type:varchar(60),required:false}
        tipo_pago_id: ~
    producto:
        id:          ~
        descripcion:  { type: varchar}
        precio:       { type: double }
        marca_id:     ~
        