propel:
    usuario:
      id:                                ~
      usuario:                           { type: varchar(32), required: true }
      clave:                             { type: varchar(40) }
      nombre:                            { type: varchar(60), required: true, primaryString: true }
      apellido:                          { type: varchar(60), required: true }
      perfil_id:                         ~
      created_at:                        ~
      updated_at:                        ~
      created_by:                        { type: varchar(32) }
      updated_by:                        { type: varchar(32) }
      _uniques:
        llave:                           [ usuario ]    
    cliente: 
        id:                              ~
        nombre:                         { type: varchar, required: true, primaryString: true }
        correo:                         { type:varchar(70) , required:false}
        direccion:                      { type:varchar(100), required:false}
        telefono:                       { type:varchar(100), required:false}
        ciudad:                         { type:varchar(50), required:false}
        observacion:                    { type:varchar(120), required:false}
        puntos:                         { type: integer, default: 0}
        nit:                            { type:varchar(120), required:false}
    detalle_pedido_proveedor:
        id:              ~
        producto_id:     ~
        cantidad:       {type:integer,required:false}
        estado:         {type:varchar(20),required:true}
        pedido_proveedor_id:   ~
    marca:
        id:        ~
        nombre:                         { type: varchar, required: true, primaryString: true }
        descripcion:    {type:varchar(60),required:false}
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    pedido_proveedor:
        id:              ~
        fecha:          {type:date,required:true}
        descripcion:    {type:varchar(25),required:false}
        estado:         {type:varchar(30),required:true}
        usuario_id:      ~
        proveedor_id:    ~
    promocion:
        id:    ~
        descripcion:    {type:varchar(70),required:false}
        fecha_inicio:   {type:date,required:true}
        fecha_fin:     {type:date,required:true}
        estado:    {type:varchar(11),required:false}
        producto_id:     ~
        descuento:      {type:decimal,required:false}
        promocion_global:         {type:boolean,required:true}
    proveedor:
        id:    ~
        nombre:                         { type: varchar, required: true, primaryString: true }
        direccion:      {type:varchar(70),required:true}
        correo_eletronico: {type:varchar(70),required:true}
        nombre_contacto: {type:varchar(70),required:false}
        telefono:       {type:varchar(30),required:true}
        ciudad:         {type: varchar(30),required:false}
        observacion:    {type:varchar(70),required:false}
        nit:                            { type: varchar(255) }
        razon_social:                   { type: varchar(255) }
        contacto:                       { type: varchar(255) }
        referencia:                     { type: varchar(255) }
    tipo_pago:
        id:     ~
        nombre:                         { type: varchar, required: true, primaryString: true }
        descripcion:    {type:varchar(70),required:false}
    tipo_producto:
        id: ~
        nombre:                         { type: varchar, required: true, primaryString: true }
        descripcion:    {type:varchar(120),required:false}
    tipo_transaccion:
        id: ~
        descripcion:    {type:varchar(60),required:true}
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    tipo_usuario:
        id:      ~
        nombre:                         { type: varchar, required: true, primaryString: true }
        descripcion:    {type:varchar(120),required:false}
    transaccion:
        id: ~
        serie: {type:varchar(120),required:false}
        documento: {type:varchar(120),required:false}
        cliente_id: ~
        usuario_id: ~
        tipo_transaccion_id: ~
        no_tarjeta: {type:varchar(60),required:false}
        total: {type:decimal,required:false}
        direccion: {type:varchar(60),required:false}
        tipo_pago_id: ~
    producto:
        id:          ~
        descripcion:                         { type: varchar, required: true, primaryString: true }
        marca_id:     ~
        tipo_producto_id: ~
        tipo_presentacion_id:                ~
        cantidad_minima:                     { type: integer, default: 20}
        imagen:                              { type: varchar}
        codigo:                              { type: varchar}
        precio:                              { type: double}
        costo:                              { type: double}
    inventario:
        id:            ~
        producto_id:   ~
        cantidad:      { type: integer}
        precio_compra: { type: double}
        proveedor_id:  ~
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    factura:
        id:           ~
        cliente_id:   ~
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
        total:                             { type: double}
        tipo_pago_id:                           ~
        activo:                            { type: boolean, default: true}
        fecha:                             { type: varchar(32)}
        serie:                             { type: varchar(100)}
        documento:                         { type: varchar(100)}
    factura_detalle:
        id:            ~
        factura_id:    ~
        producto_id:   ~
        proveedor_id:  ~
        cantidad:             { type: integer}
        precio_unitario:      { type: double}
    bitacora_cambios:
        id:           ~
        modelo:      { type: varchar}
        descripcion:  { type: varchar}
        ip:           { type: varchar}
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    tipo_presentacion:
        id:  ~
        descripcion:            { type: varchar(250), primaryString: true }
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    menu:
        id:  ~
        descripcion:                       { type: varchar(250), primaryString: true }
        modulo:                            { type: varchar(250) }
        accion:                            { type: varchar(250) }
        icono:                             { type: varchar(100) }
        orden:                             { type: integer }
        superior:                          { type: integer }
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
    perfil:
        id:  ~
        descripcion:            { type: varchar(250), primaryString: true }
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
    perfil_menu:
        id:  ~
        perfil_id:                         ~
        menu_id:                           ~
        created_at:                        ~
        updated_at:                        ~
        created_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }
        updated_by:                        { type: varchar(32) }