generator:
  class: sfPropelGenerator
  param:
    model_class:           usuario
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              usuario
    plural:                usuarios
    route_prefix:          usuario
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
