generator:
  class: sfPropelGenerator
  param:
    model_class:           usuario
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              usuario
    plural:                usuarios
    route_prefix:          usuario
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:   ~
       
        
      fields:  ~
      list:
        title:             Listado de Usuarios
        display:           [usuario,  nombre, apellido, perfil]
        object_actions:
           _edit:           ~
           _delete:         ~
           cambio_clave:
             label:         Cambio de Clave
             action:        clave
             params:         class=btn btn-xs btn-default
      filter:
         display:           [usuario,  nombre, apellido, perfil_id]
      form:               ~
      edit:
        title:           Editar Usuario
        display:           [usuario, nombre,apellido, perfil_id]
      new:
        title:           Nuevo Usuario
        display:           [usuario, clave, nombre,apellido, perfil_id]
