<?php



/**
 * This class defines the structure of the 'jugador_mesa' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 10/31/15 22:35:50
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class JugadorMesaTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.JugadorMesaTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('jugador_mesa');
        $this->setPhpName('JugadorMesa');
        $this->setClassname('JugadorMesa');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('MESA_ID', 'MesaId', 'INTEGER', 'mesa', 'ID', false, null, null);
        $this->addColumn('ESTADO', 'Estado', 'VARCHAR', false, 100, null);
        $this->addForeignKey('JUGADOR_ID', 'JugadorId', 'INTEGER', 'jugador', 'ID', false, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('CREATED_BY', 'CreatedBy', 'VARCHAR', false, 255, null);
        $this->addColumn('UPDATED_BY', 'UpdatedBy', 'VARCHAR', false, 255, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Mesa', 'Mesa', RelationMap::MANY_TO_ONE, array('mesa_id' => 'id', ), null, null);
        $this->addRelation('Jugador', 'Jugador', RelationMap::MANY_TO_ONE, array('jugador_id' => 'id', ), null, null);
        $this->addRelation('Turno', 'Turno', RelationMap::ONE_TO_MANY, array('id' => 'jugador_mesa_id', ), null, null, 'Turnos');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
        );
    } // getBehaviors()

} // JugadorMesaTableMap
