generator:
  class: sfPropelGenerator
  param:
    model_class:           menu
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              menu
    plural:                menus
    route_prefix:          menu
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:           [descripcion, modulo, accion, superior,orden, icono]
        title:             Listado de Menús
      filter:
        display:           [descripcion]
      form:
        display:           [descripcion, modulo, accion, superior,orden, icono]
      edit:
        title:              Editar Menú
      new:
        title:              Nuevo Menú
