<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/11/10 12:36:30
sfConfig::add(array(
  'mod_pedido_proveedor_enabled' => true,
  'mod_pedido_proveedor_view_class' => 'sfPHP',
));
