generator:
  class: sfPropelGenerator
  param:
    model_class:           proveedor
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              proveedor
    plural:                proveedors
    route_prefix:          proveedor
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        direccion:         
          label:          Dirección
        telefono:
          label:          Teléfono
      list:
        title:             Listado de Proveedores
        display:           [nombre, direccion, telefono, ciudad, nit, razon_social]
      filter:
        display:           [nombre, direccion, telefono, ciudad, nit, razon_social, contacto, referencia]
      form:
        display:           [nombre, direccion, telefono, ciudad, nit, razon_social, contacto, referencia]
      edit:
        title:             Editar Proveedor
      new:
        title:             Nuevo Proveedor
