generator:
  class: sfPropelGenerator
  param:
    model_class:           tipoUsuario
    theme:                 fusion
    non_verbose_templates: true
    with_show:             false
    singular:              tipoUsuario
    plural:                tipoUsuarios
    route_prefix:          tipo_usuario
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:             Listado de Tipos de Usuario
        display:           [nombre, descripcion]
      filter:
        display:           [nombre, descripcion]
      form:
        display:           [nombre, descripcion]
      edit:
        title:             Editar tipo de usuario
      new:
        title:             Nuevo tipo de Usuario
