<?php

/**
 * Skeleton subclass for representing a row from the 'proveedor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 11/06/15 06:34:57
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Proveedor extends BaseProveedor {

    public function save(PropelPDO $con = null) {
        $BitacoraCambios = new BitacoraCambios();
        $BitacoraCambios->setModelo('Proveedor');
        $BitacoraCambios->setIp(sfContext::getInstance()->getRequest()->getRemoteAddress());
        if ($this->isNew()) {
            $BitacoraCambios->setDescripcion('Creacion de Proveedor: ' . $this->getNombre());
        } else {
            $BitacoraCambios->setDescripcion('Modificacion de Proveedor: ' . $this->getNombre());
        }
        $Usuario = UsuarioQuery::create()->findOneById(sfContext::getInstance()->getUser()->getAttribute('usuario', null, 'seguridad'));
        if ($Usuario) {
            $BitacoraCambios->setCreatedBy($Usuario->getUsuario());
        }
        $BitacoraCambios->save();
        return parent::save($con);
    }

}
